create table itens_pedido (
    id_produto bigint not null,
    quantidade integer,
    pedido_id bigint,
    primary key (id_produto)
);

create table pedidos (
     id_pedido bigint generated by default as identity,
     id_pagamento bigint,
     id_cliente bigint not null,
     status tinyint check (status between 0 and 4),
     primary key (id_pedido)
);

alter table if exists itens_pedido
    add constraint FK42mycompce3b7yt3l6ukdwsxy
    foreign key (pedido_id)
    references pedidos