create table pedidos (
    id_pedido bigint generated by default as identity,
    id_pagamento bigint,
    id_cliente bigint not null,
    status tinyint check (status between 0 and 4),
    primary key (id_pedido)
);

create table itens_pedido (
    pedido_id bigint not null,
    id_produto bigint not null,
    quantidade integer,
    primary key (pedido_id, id_produto),
    foreign key (pedido_id) references pedidos(id_pedido)
);