create table pedidos (
     id_pedido bigint generated by default as identity primary key,
     id_cliente bigint not null,
     id_pagamento bigint,
     status tinyint
);

create table itens_pedido (
      id bigint generated by default as identity primary key,
      pedido_id bigint not null,
      id_produto bigint not null,
      quantidade integer not null,
      foreign key (pedido_id) references pedidos(id_pedido)
);